import type { Metadata } from 'next'
import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import SupabaseProvider from '@/providers/SupabaseProvider'
import UserProvider from '@/providers/UserProvider'
import AuthenticationHandler from '@/components/AuthenticationHandler'
import Provider from '@/providers/Provider'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Email AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>
        <Provider>
          <SupabaseProvider>
            <AuthenticationHandler />
            <UserProvider>{children}</UserProvider>
          </SupabaseProvider>
        </Provider>
      </body>
    </html>
  )
}
